### ISSUE TITLE
Docs site showing styler docs for server side

### ISSUE THREAD

**Issue by cabbiepete** [composi/core#1]
https://composi.github.io/en/docs/server-side/install.html

Shows the same content as https://composi.github.io/en/docs/styler/install.html

Likewise for the usage page.

**Comment by cabbiepete** [comment]
Screen shot of server-side/install.html at the time of posting this issue (in case this is updated automatically and fixed before the issue is noticed)

![screen shot 2019-01-05 at 11 09 24 am](https://user-images.githubusercontent.com/106585/50713572-654d7200-10da-11e9-8ea9-530cb2997ed4.png)

First couple lines correct but the rest of the content is for the styler package.

**Comment by rbiggs** [comment]
Egads!!! My bad. I pushed that feature out in a hurry in the middle of the night for a user who was pressuring me for a way to render components server-side. Give me a bit and I’ll push the correct docs up.

**Comment by cabbiepete** [comment]
All good.
