### ISSUE TITLE
[??] document use with expression functions

### ISSUE THREAD

**Issue by brody2consult** [composi/core#4]
for example (*not tested*):

```js
const Title = (greet) => (
  h(
    'nav',
    {
      class: 'heading'
    },
    [
      // h(...)
    ]
  )
)
```

more functional, less imperative

**Comment by rbiggs** [comment]
Yes, that pattern works, but it's harder to debug in the browser console because the function is anonymous.

**Comment by brody2consult** [comment]
I thought that modern JS engines would detect this kind of a pattern as a function declaration (Babel JS seems to do this), oh well. Closing for now.

**Comment by rbiggs** [comment]
To be honest, I do use the pattern occasionally myself. But I tend to use named functions as much as possible. I know it's fashionable for devs these days to use arrow functions as much as possible. I prefer to use them for what they were designed for: lambdas.
